package ua.hillel.lessons.lesson8.demos._02_try_catch_multi;

// Обробка винятку без збереження порядку винятків,
// тобто від конкретного до загального.
public class Main05 {

    public static void main(String[] args) {

//        try {
//            int[] arr = new int[5];
//            arr[5] = 30 / 0;
//        } catch (Exception e) {
//            System.out.println("Common task completed");
//        } catch (ArithmeticException e) {
//            System.out.println("Task 1 completed");
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.println("Task 2 completed");
//        }

        System.out.println("Further down the code...");
    }
}
